Update Solax Inverter.xml
taphome-official/packetparser_templates pull request #15
Opened 2023-05-04 07:49 UTC by Tizikadam

Changed some names to make the instructions more clear, updated some devices, fixed issues

2023-06-22 11:44 UTC, marian-blazicek requested changes

2023-06-22 11:44 UTC, marian-blazicek commented on Solax/Solax Inverter.xml
> +  <Template revision="1.0" id = "0409e0d1-59f4-48b4-ac6b-a4c890546c01">>
>>
je asi preklep

2023-06-22 11:44 UTC, marian-blazicek commented on Solax/Solax Inverter.xml
> +<Templates format="2" protocolVersion="76">
zniz to na 73, aby to islo importovat aj v starsich apkach

2023-06-22 11:44 UTC, marian-blazicek commented on Solax/Solax Inverter.xml
> +        <CustomVariables>[{"Name":"ans","ValueTypeId":2,"NumericValue":0,"StringValue":"0"},{"Name":"tokenID","ValueTypeId":2,"NumericValue":0,"StringValue":"0"},{"Name":"RegistrationNumber","ValueTy
RegistrationNumber by nemal byt import parameter ?

2023-06-22 11:45 UTC, marian-blazicek commented on Solax/Solax Inverter.xml
> +  <Template revision="1.0" id = "0409e0d1-59f4-48b4-ac6b-a4c890546c01">>
na konci ">>"

2023-10-25 07:40 UTC, Tizikadam commented on Solax/Solax Inverter.xml
> +        <CustomVariables>[{"Name":"ans","ValueTypeId":2,"NumericValue":0,"StringValue":"0"},{"Name":"tokenID","ValueTypeId":2,"NumericValue":0,"StringValue":"0"},{"Name":"RegistrationNumber","ValueTy
Normalne je tam premenna, vsetko frci

2023-10-25 07:40 UTC, Tizikadam commented
Pridal som sem aj tu shelly plus i4

2023-11-06 13:06 UTC, marian-blazicek approved these changes

2023-11-06 13:06 UTC, marian-blazicek commented on Shelly/Shelly Plus i4.xml
> +        <IpAddress>192.168.1.14</IpAddress>
chybaju import parametre

2023-12-05 08:56 UTC, marian-blazicek commented
Zatvaram. Pridal som to mimo PR.

2023-12-05 08:56 UTC, closed without merging